-- MySQL Script generated by MySQL Workbench
-- Tue Dec  1 21:10:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DBPruebaTecnica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBPruebaTecnica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBPruebaTecnica` DEFAULT CHARACTER SET utf8 ;
USE `DBPruebaTecnica` ;

-- -----------------------------------------------------
-- Table `DBPruebaTecnica`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBPruebaTecnica`.`Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `cedula` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `area_trabajo` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `Empleadocol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBPruebaTecnica`.`Accidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBPruebaTecnica`.`Accidente` (
  `idAccidente` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `gravedad` VARCHAR(45) NOT NULL,
  `fecha_evento` VARCHAR(45) NOT NULL,
  `sitio_accidente` VARCHAR(45) NOT NULL,
  `tipo_accidente` VARCHAR(45) NOT NULL,
  `lesion_accidente` VARCHAR(45) NOT NULL,
  `parte_afectada` VARCHAR(45) NOT NULL,
  `agente` VARCHAR(45) NOT NULL,
  `mecanismo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `incapacidad` VARCHAR(45) NULL,
  `dias_incapacidad` INT NULL,
  `idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idAccidente`),
  INDEX `fk_Accidente_Empleado_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `fk_Accidente_Empleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `DBPruebaTecnica`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
